"""Prompt templates for file and folder classification.

Each builder produces a self-contained prompt that includes the full taxonomy
with descriptions so the LLM understands every category.
"""

from __future__ import annotations

from src.db.models import FileSummary, FolderSummary, WavefrontFolderSummary

# ---------------------------------------------------------------------------
# Taxonomy descriptions (shared reference for prompts)
# ---------------------------------------------------------------------------

FOLDER_PURPOSE_TAXONOMY = {
    "irreplaceable_personal": "Unique personal files that cannot be recovered if lost (photos, personal documents, journals, etc.)",
    "important_personal": "Personal files that are important but potentially recoverable from other sources",
    "project_or_work": "Work projects, code repositories, professional documents",
    "reinstallable_software": "Applications and software that can be re-downloaded or reinstalled",
    "media_archive": "Media collections (music, movies, etc.) that may be replaceable from other sources",
    "redundant_duplicate": "Files or folders that are duplicates of content already backed up or classified elsewhere",
    "system_or_temp": "Operating system files, temporary files, caches, system junk",
    "unknown_review_needed": "Items that could not be confidently classified and need human review",
}

FILE_CLASS_TAXONOMY = {
    "personal_document": "Personal documents such as letters, journals, notes, resumes, tax forms",
    "personal_photo": "Personal photographs and images taken by the user",
    "personal_video": "Personal videos recorded by the user",
    "personal_audio": "Personal audio recordings (voice memos, music compositions)",
    "work_document": "Professional or work-related documents, spreadsheets, presentations",
    "source_code": "Programming source code files, scripts, configuration files for projects",
    "project_asset": "Assets belonging to a project (design files, data files, build artifacts)",
    "application_binary": "Installed application executables and libraries",
    "application_cache": "Application cache files, temp data, logs generated by software",
    "system_file": "Operating system files, drivers, system configuration",
    "media_music": "Music files from collections or downloads",
    "media_video": "Video files from collections or downloads (movies, TV shows)",
    "media_ebook": "E-books and digital publications",
    "archive_compressed": "Compressed archives (zip, tar, rar) — contents unknown without inspection",
    "database_file": "Database files (SQLite, Access, etc.)",
    "backup_image": "Disk images, system backups, VM snapshots",
    "unknown": "File type could not be determined with confidence",
}


# ---------------------------------------------------------------------------
# Prompt builders
# ---------------------------------------------------------------------------


def _format_file_taxonomy() -> str:
    """Render the file class taxonomy as a numbered list for the prompt."""
    lines: list[str] = []
    for i, (key, desc) in enumerate(FILE_CLASS_TAXONOMY.items(), 1):
        lines.append(f"  {i}. {key} — {desc}")
    return "\n".join(lines)


def _format_folder_taxonomy() -> str:
    """Render the folder purpose taxonomy as a numbered list for the prompt."""
    lines: list[str] = []
    for i, (key, desc) in enumerate(FOLDER_PURPOSE_TAXONOMY.items(), 1):
        lines.append(f"  {i}. {key} — {desc}")
    return "\n".join(lines)


def build_file_classification_prompt(summaries: list[FileSummary]) -> str:
    """Build a prompt that presents file metadata and asks for File_Class labels.

    The prompt includes the full File_Class taxonomy with descriptions and a
    JSON array of file summaries.  The LLM is instructed to return a JSON array
    of classification objects.
    """
    taxonomy_text = _format_file_taxonomy()

    file_entries: list[str] = []
    for s in summaries:
        parts = [
            f"    entry_id: {s.entry_id}",
            f"    path: {s.path}",
            f"    name: {s.name}",
            f"    extension: {s.extension or '(none)'}",
            f"    size_bytes: {s.size_bytes}",
            f"    last_modified: {s.last_modified.isoformat() if s.last_modified else 'unknown'}",
        ]
        file_entries.append("\n".join(parts))

    files_text = "\n  ---\n".join(file_entries)

    return f"""You are a file classification assistant. Your task is to classify each file into exactly one category from the File_Class taxonomy below, and assign a confidence score between 0.0 and 1.0.

## File_Class Taxonomy

{taxonomy_text}

## Files to Classify

{files_text}

## Instructions

For each file, determine the most appropriate file_class from the taxonomy above based on the file's path, name, extension, size, and last modified date. Assign a confidence score (0.0 = no confidence, 1.0 = certain). Provide a brief reasoning for your classification.

Return a JSON array where each element has these fields:
- entry_id (int): the entry_id from the input
- file_class (string): one of the taxonomy keys listed above
- confidence (float): between 0.0 and 1.0
- reasoning (string): brief explanation

Return ONLY the JSON array, no other text."""


def build_folder_classification_prompt(summary: FolderSummary) -> str:
    """Build a prompt with folder contents summary, asking for Folder_Purpose.

    The prompt includes the full Folder_Purpose_Taxonomy with descriptions and
    aggregated folder statistics (file count, total size, extension breakdown,
    subfolder names).
    """
    taxonomy_text = _format_folder_taxonomy()

    # Format file type distribution
    if summary.file_type_distribution:
        dist_lines = [
            f"    {ext}: {count} files"
            for ext, count in sorted(
                summary.file_type_distribution.items(),
                key=lambda x: x[1],
                reverse=True,
            )
        ]
        dist_text = "\n".join(dist_lines)
    else:
        dist_text = "    (no files)"

    # Format subfolder names
    if summary.subfolder_names:
        subfolder_text = ", ".join(summary.subfolder_names[:20])
        if len(summary.subfolder_names) > 20:
            subfolder_text += f" ... and {len(summary.subfolder_names) - 20} more"
    else:
        subfolder_text = "(none)"

    return f"""You are a folder classification assistant. Your task is to classify this folder into exactly one category from the Folder_Purpose taxonomy below, and assign a confidence score between 0.0 and 1.0.

## Folder_Purpose Taxonomy

{taxonomy_text}

## Folder to Classify

  entry_id: {summary.entry_id}
  path: {summary.path}
  name: {summary.name}
  file_count: {summary.file_count}
  total_size_bytes: {summary.total_size_bytes}

  File type distribution:
{dist_text}

  Subfolders: {subfolder_text}

## Instructions

Based on the folder's path, name, contents (file types and sizes), and subfolder structure, determine the most appropriate folder_purpose from the taxonomy above. Assign a confidence score (0.0 = no confidence, 1.0 = certain). Provide a brief reasoning.

Return a JSON object with these fields:
- entry_id (int): the entry_id from the input
- folder_purpose (string): one of the taxonomy keys listed above
- confidence (float): between 0.0 and 1.0
- reasoning (string): brief explanation

Return ONLY the JSON object, no other text."""


def build_wavefront_folder_prompt(summary: WavefrontFolderSummary) -> str:
    """Build a prompt for wavefront folder classification.

    Includes:
    - Folder purpose taxonomy
    - Triage signal explanation (include/exclude/descend)
    - Tree metadata (child count, descendant counts)
    - Parent classification context (if available)
    - Request for dual confidence scores
    - Combined reasoning for both classification and decision
    """
    taxonomy_text = _format_folder_taxonomy()

    # Format file type distribution
    if summary.file_type_distribution:
        dist_lines = [
            f"    {ext}: {count} files"
            for ext, count in sorted(
                summary.file_type_distribution.items(),
                key=lambda x: x[1],
                reverse=True,
            )
        ]
        dist_text = "\n".join(dist_lines)
    else:
        dist_text = "    (no files)"

    # Format subfolder names
    if summary.subfolder_names:
        subfolder_text = ", ".join(summary.subfolder_names[:20])
        if len(summary.subfolder_names) > 20:
            subfolder_text += f" ... and {len(summary.subfolder_names) - 20} more"
    else:
        subfolder_text = "(none)"

    # Tree metadata — show value or "unknown" for None
    child_count_str = str(summary.child_count) if summary.child_count is not None else "unknown"
    descendant_file_str = str(summary.descendant_file_count) if summary.descendant_file_count is not None else "unknown"
    descendant_folder_str = str(summary.descendant_folder_count) if summary.descendant_folder_count is not None else "unknown"

    # Parent context section (only when parent_classification is not None)
    parent_section = ""
    if summary.parent_classification is not None:
        parent_section = f"""
## Parent Folder Context

  Parent classification: {summary.parent_classification}
  Parent decision: {summary.parent_decision or "unknown"}
"""

    return f"""You are a folder classification and triage assistant. Your task is to classify this folder into one category from the Folder_Purpose taxonomy below, AND decide a triage signal for the backup wavefront traversal.

## Folder_Purpose Taxonomy

{taxonomy_text}

## Triage Signals

You must assign one of these triage decisions:
  - include: Back up the entire subtree. All files and subfolders are included without further classification.
  - exclude: Skip the entire subtree. Nothing in this folder tree will be backed up.
  - descend: Classify children individually. Look deeper into subfolders before deciding.

## Folder to Classify

  entry_id: {summary.entry_id}
  path: {summary.path}
  name: {summary.name}
  depth: {summary.depth}
  size_bytes: {summary.size_bytes}

  Tree metadata:
    child_count: {child_count_str}
    descendant_file_count: {descendant_file_str}
    descendant_folder_count: {descendant_folder_str}

  File type distribution:
{dist_text}

  Subfolders: {subfolder_text}
{parent_section}
## Instructions

Based on the folder's path, name, contents, tree metadata, and parent context (if provided), determine:
1. The most appropriate folder_purpose from the taxonomy above.
2. The triage decision (include, exclude, or descend).

Assign two confidence scores:
- classification_confidence: how confident you are in the folder_purpose (0.0–1.0)
- decision_confidence: how confident you are in the triage decision (0.0–1.0)

Provide a single reasoning string that explains both the classification and the triage decision.

Return a JSON object with these fields:
- entry_id (int): the entry_id from the input
- folder_purpose (string): one of the taxonomy keys listed above
- decision (string): one of "include", "exclude", "descend"
- classification_confidence (float): between 0.0 and 1.0
- decision_confidence (float): between 0.0 and 1.0
- reasoning (string): combined classification and decision reasoning

Return ONLY the JSON object, no other text."""
